source 'https://rubygems.org'

gem 'activerecord'
gem 'pg'

gem 'rspec'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'rake'
gem 'rack'
gem 'rack-test'
gem "paperclip", git: "git://github.com/thoughtbot/paperclip.git"
gem 'faker'